trigger: none

pool: Git_Agent_Pool

stages:
- stage: terraforminitplan
  displayName:  terraform installer
  jobs:
   - job: setupterraforminstaller
     displayName: terraform installer
     steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
     
          